### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by alexvndre** [rowellx68/pgorate#2]
Hi,

It's possible to contribute to your project?

I added IV percent.
- [Pokémons's list](http://i.imgur.com/HIN2yvj.png)
- [Filters](http://i.imgur.com/6rSb06X.png)

And I would add Pokémon's details and add user's inventory.

Thanks!

**Comment by rowellx68** [comment]
Hi!

Contributing is ALWAYS welcome. Just do a PR and we'll merge it in.

Looking good btw 👍

Recent [commit](https://github.com/rowellx68/pgorate/commit/916fc31acaedb8e581e90254a4fa62eaecd40a1b) implements filtering by level and IV %. You should still do a PR as the IV% is not shown via the UI.

EDIT: Link to commit

**Comment by alexvndre** [comment]
Ok cool, can you send email an email please (you can find it on my profile page) ? I would speak with you that you want implement and help you.
